services:
  app:
    build: ./services/app/
    command: gunicorn wsgi:app --bind 0.0.0.0:8080 --log-level=debug --workers=4
    links:
      - db
    ports:
      - 8080:8080
    env_file:
      - .env.prod

  db:
    image: mysql:8.0
    ports:
      - "32000:3306"
    env_file:
      - .env.db.prod
    volumes:
      - ./services/db:/docker-entrypoint-initdb.d/:ro

  nginx:
    build: ./services/nginx/
    ports:
      - 80:80
    depends_on:
      - app