services:
  app:
    build: ./
    command: gunicorn --bind 0.0.0.0:5000 app:create_app()
    links:
      - db
    expose:
      - 5000
    env_file:
      - .env.prod

  db:
    image: mysql:8.0
    ports:
      - "32000:3306"
    env_file:
      - .env.db.prod
    volumes:
      - ./services/db:/docker-entrypoint-initdb.d/:ro

  nginx:
    build: ./services/nginx/
    ports:
      - 1337:80
    depends_on:
      - app

