services:
  app:
    build: ./services/app/
    command: gunicorn 'wsgi:create_app()' --bind 0.0.0.0:8080 --log-level=debug --workers=1
    links:
      - db
    ports:
      - 8080:8080
    env_file:
      - .env.dev

  db:
    build: ./services/db/
    ports:
      - "32000:3306"
    env_file:
      - .env.db
    volumes:
      - ./services/db:/docker-entrypoint-initdb.d/:ro

  nginx:
    build: ./services/nginx/
    ports:
      - 1337:8080
    depends_on:
      - app