version: "2"
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    links:
      - db
    ports:
      - "5000:5000"
    env_file:
      - .env.prod
  db:
    image: mysql:8.0
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${db_password}"
    volumes:
      - ./services/db:/docker-entrypoint-initdb.d/:ro