name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    env:
      PROJECT_REGISTRY_PATH: "ghcr.io/benvneal88/ncaa-bb-fantasy-manager"
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
  
    - name: Build & Push App Image
      env:
        IMAGE_NAME: app
      run: |
        docker build -f services/app/Dockerfile services/app/ -t $PROJECT_REGISTRY_PATH/$IMAGE_NAME:latest 
        docker push $PROJECT_REGISTRY_PATH/$IMAGE_NAME:latest
    
    - name: Build & Push Rerverse Proxy Image
      env:
        IMAGE_NAME: reverse-proxy
      run: |
        docker build -f services/app/Dockerfile services/nginix/ -t $PROJECT_REGISTRY_PATH/$IMAGE_NAME:latest 
        docker push $PROJECT_REGISTRY_PATH/$IMAGE_NAME:latest
